version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    networks:
      - spark-network

  spark-master:
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "8080:8080"
      - "7077:7077"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    restart: unless-stopped
    networks:
      - spark-network

  spark-worker:
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --webui-port 8082
    ports:
      - "8082:8082"
    depends_on:
      - spark-master
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '3'
    restart: unless-stopped
    networks:
      - spark-network

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    command: webserver --port 8083 --workers 2
    ports:
      - "8081:8083"
    volumes:
      - ../../airflow/dags:/opt/airflow/dags:ro
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW__WEBSERVER__BASE_URL=https://af.yoyorace.tech
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    restart: unless-stopped
    networks:
      - spark-network

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    command: scheduler
    volumes:
      - ../../airflow/dags:/opt/airflow/dags:ro
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  postgres_data: